CREATE TABLE TFPC_COMPAÑIA (
    COD_COMPAÑIA NUMBER,
    NOMBRE_COMPAÑIA VARCHAR2(50),
    CONSTRAINT PK_COMPAÑIA PRIMARY KEY(COD_COMPAÑIA)
);

CREATE TABLE TFPC_PERSONAL (
    COD_PERSONAL NUMBER,
    RUT_PERSONAL NUMBER,
    NOMBRE VARCHAR2(50),
    APELLIDO_PATERNO VARCHAR2(50),
    APELLIDO_MATERNO VARCHAR2(50),
    CONTACTO NUMBER,
    DIRECCION VARCHAR2(100),
    CONSTRAINT PK_PERSONAL PRIMARY KEY(COD_PERSONAL)
);

CREATE TABLE TFPC_ESPECIALIDAD (
    COD_ESPECIALIDAD NUMBER,
    NOMBRE_ESPECIALIDAD VARCHAR2(50),
    CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY(COD_ESPECIALIDAD)
);

CREATE TABLE TFPC_EQUIPAMIENTO (
    COD_EQUIPAMIENTO NUMBER,
    NOMBRE_EQUIPAMIENTO VARCHAR2(50),
    CONSTRAINT PK_EQUIPAMIENTO PRIMARY KEY(COD_EQUIPAMIENTO)
);

CREATE TABLE TFPC_MEDICO (
    COD_MEDICO NUMBER,
    COD_PERSONAL NUMBER,
    COD_ESPECIALIDAD NUMBER,
    CONSTRAINT PK_MEDICO PRIMARY KEY (COD_MEDICO),
    CONSTRAINT FK_MEDICO_PERSONAL FOREIGN KEY (COD_PERSONAL) REFERENCES TFPC_PERSONAL(COD_PERSONAL),
    CONSTRAINT FK_MEDICO_ESPECIALIDAD FOREIGN KEY (COD_ESPECIALIDAD) REFERENCES TFPC_ESPECIALIDAD(COD_ESPECIALIDAD)
);

CREATE TABLE MJVA_PACIENTE(
    RUT_PACIENTE NUMBER,
    NOMBRE_PACIENTE VARCHAR2(30),
    APELLIDO_PATERNO VARCHAR2(25),
    APELLIDO_MATERNO VARCHAR2(25),
    FECHA_NACIMIENTO DATE,
    CONTACTO NUMBER,
    DIRECCION VARCHAR2(100),
    CONSTRAINT PK_RUT_PACIENTE PRIMARY KEY (RUT_PACIENTE)
);

CREATE TABLE TFPC_SEGURO_MEDICO (
    COD_SEGURO NUMBER,
    RUT_PACIENTE NUMBER,
    COD_COMPAÑIA NUMBER,
    CONTACTO NUMBER,
    CONSTRAINT PK_SEGURO PRIMARY KEY(COD_SEGURO),
    CONSTRAINT FK_SEGURO_PACIENTE FOREIGN KEY (RUT_PACIENTE) REFERENCES MJVA_PACIENTE(RUT_PACIENTE),
    CONSTRAINT FK_SEGURO_COMPAÑIA FOREIGN KEY (COD_COMPAÑIA) REFERENCES TFPC_COMPAÑIA(COD_COMPAÑIA)
);

CREATE TABLE TFPC_SALA_DE_EXAMEN (
    COD_SALA NUMBER,
    FECHA DATE,
    HORARIO DATE,
    COD_EQUIPAMIENTO NUMBER,
    RUT_PACIENTE NUMBER,
    COD_MEDICO NUMBER,
    CONSTRAINT PK_SALA PRIMARY KEY (COD_SALA),
    CONSTRAINT FK_SALA_EQUIPAMIENTO FOREIGN KEY (COD_EQUIPAMIENTO) REFERENCES TFPC_EQUIPAMIENTO(COD_EQUIPAMIENTO),
    CONSTRAINT FK_SALA_RUT_PACIENTE FOREIGN KEY (RUT_PACIENTE) REFERENCES MJVA_PACIENTE(RUT_PACIENTE),
    CONSTRAINT FK_SALA_RUT_MEDICO FOREIGN KEY (COD_MEDICO) REFERENCES TFPC_MEDICO(COD_MEDICO)
);

CREATE TABLE TFPC_EXAMEN (
    COD_EXAMEN NUMBER,
    NOMBRE VARCHAR2(50),
    DESCRIPCION CLOB,
    FECHA_EXAMEN DATE,
    COD_SALA NUMBER,
    CONSTRAINT PK_EXAMEN PRIMARY KEY(COD_EXAMEN),
    CONSTRAINT FK_EXAMEN FOREIGN KEY(COD_SALA) REFERENCES TFPC_SALA_DE_EXAMEN(COD_SALA)
);

CREATE TABLE EIFA_FORMA_DE_PAGO (
    COD_FORMA_PAGO NUMBER,
    MEDIO_DE_PAGO VARCHAR2(50),
    CUOTAS NUMBER,
    --UTILZIAR COMO BOOLEANO
    NUM_CUOTAS NUMBER,
    VALOR_CUOTA NUMBER,
    CONSTRAINT PK_MEDIO_DE_PAGO PRIMARY KEY (COD_FORMA_PAGO)
);

CREATE TABLE EIFA_AUXILIARES (
    COD_AUXILIAR NUMBER,
    COD_CARGO NUMBER,
    COD_PERSONAL NUMBER,
    CONSTRAINT PK_AUXILIARES PRIMARY KEY (COD_AUXILIAR)
);

CREATE TABLE EIFA_DETALLES_CARGO (
    COD_CARGO NUMBER,
    COD_AUXILIAR NUMBER,
    NOMBRE_CARGO VARCHAR2(50),
    CONSTRAINT PK_DETALLES_CARGO PRIMARY KEY (COD_CARGO)
);

ALTER TABLE
    EIFA_AUXILIARES
ADD
    CONSTRAINT FK_AUXILIARES_CARGO FOREIGN KEY (COD_CARGO) REFERENCES EIFA_DETALLES_CARGO(COD_CARGO);

CREATE TABLE EIFA_HORARIOS (
    COD_HORARIO NUMBER,
    COD_AUXILIAR NUMBER,
    COD_MEDICO NUMBER,
    CONSTRAINT PK_HORARIOS PRIMARY KEY (COD_HORARIO),
    CONSTRAINT FK_HORARIOS_AUXILIAR FOREIGN KEY (COD_AUXILIAR) REFERENCES EIFA_AUXILIARES(COD_AUXILIAR),
    CONSTRAINT FK_HORARIOS_MEDICO FOREIGN KEY (COD_MEDICO) REFERENCES TFPC_MEDICO(COD_MEDICO)
);

CREATE TABLE EIFA_DETALLES_HORARIO (
    COD_DETALLE_HORARIO NUMBER,
    COD_HORARIO NUMBER,
    DIA_SEMANA VARCHAR2(15),
    HORA_INICIO TIMESTAMP,
    HORA_FIN TIMESTAMP,
    CONSTRAINT PK_DETALLES_HORARIO PRIMARY KEY (COD_DETALLE_HORARIO),
    CONSTRAINT FK_DETALLESHORARIO_HORARIO FOREIGN KEY (COD_HORARIO) REFERENCES EIFA_HORARIOS(COD_HORARIO)
);

CREATE TABLE EIFA_MEDICAMENTOS (
    COD_MEDICAMENTO NUMBER,
    VALOR NUMBER,
    NOMBRE_MEDICAMENTO VARCHAR2(50),
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (COD_MEDICAMENTO)
);

CREATE TABLE EIFA_INDICACIONES (
    COD_INDICACIONES NUMBER,
    COD_MEDICAMENTO NUMBER,
    INDICACIONES CLOB,
    CONSTRAINT PK_INDICACIONES PRIMARY KEY (COD_INDICACIONES),
    CONSTRAINT FK_INDICACIONES_MEDICAMENTO FOREIGN KEY (COD_MEDICAMENTO) REFERENCES EIFA_MEDICAMENTOS(COD_MEDICAMENTO)
);

CREATE TABLE MJVA_PACIENTE(
    RUT_PACIENTE NUMBER,
    NOMBRE_PACIENTE VARCHAR2(30),
    APELLIDO_PATERNO VARCHAR2(25),
    APELLIDO_MATERNO VARCHAR2(25),
    FECHA_NACIMIENTO DATE,
    CONTACTO NUMBER,
    DIRECCION VARCHAR2(100),
    CONSTRAINT PK_RUT_PACIENTE PRIMARY KEY (RUT_PACIENTE)
);

CREATE TABLE MJVA_ENFERMEDADES(
    COD_ENFERMEDADES NUMBER,
    NOMBRE_ENFERMEDAD VARCHAR2(50),
    DETALLE CLOB,
    CONSTRAINT PK_COD_ENFERMEDADES PRIMARY KEY(COD_ENFERMEDADES)
);

CREATE TABLE MJVA_EQUIPO_MEDICO(
    COD_EQUIPO_MEDICO NUMBER,
    NOMBRE VARCHAR2(80),
    DETALLE CLOB,
    CONSTRAINT PK_COD_EQUIPO_MEDICO PRIMARY KEY(COD_EQUIPO_MEDICO)
);

CREATE TABLE MJVA_VALOR(
    COD_VALOR NUMBER,
    VALOR NUMBER,
    CONSTRAINT PK_COD_VALOR PRIMARY KEY(MJVA_VALOR)
);

CREATE TABLE MJVA_TIPO_PROCEDIMIENTO(
    COD_TIPO_PROCEDIMIENTO NUMBER,
    TIPO_PROCEDIMIENTO VARCHAR2(100),
    NOMBRE_PROCEDIMIENTO VARCHAR2(50),
    CONSTRAINT PK_COD_TIPO_PROCEDIMIENTO PRIMARY KEY(COD_TIPO_PROCEDIMIENTO)
);

CREATE TABLE MJVA_PACIENTE(
    RUT_PACIENTE NUMBER,
    NOMBRE_PACIENTE VARCHAR2(30),
    APELLIDO_PATERNO VARCHAR2(25),
    APELLIDO_MATERNO VARCHAR2(25),
    FECHA_NACIMIENTO DATE,
    CONTACTO NUMBER,
    DIRECCION VARCHAR2(100),
    CONSTRAINT PK_RUT_PACIENTE PRIMARY KEY (RUT_PACIENTE)
);

CREATE TABLE MJVA_TRATAMIENTOS(
    COD_TRATAMIENTOS NUMBER,
    COD_DIAGNOSTICO NUMBER,
    DETALLE CLOB,
    FECHA DATE,
    CONSTRAINT PK_TRATAMIENTOS PRIMARY KEY(COD_TRATAMIENTOS)
);

CREATE TABLE EIFA_DESCRIPCION_DEL_DIAGNOSTICO(
    COD_DESCRIPCION NUMBER,
    COD_TRATAMIENTO NUMBER,
    COD_DIAGNOSTICO NUMBER,
    DESCRIPCION CLOB,
    CONSTRAINT PK_DESCRIPCION_DIAGNOSTICO PRIMARY KEY(COD_DESCRIPCION),
    CONSTRAINT FK_DESCRIPCION_DIAGNOSTICO_TRATAMIENTO FOREIGN KEY (COD_TRATAMIENTO) REFERENCES MJVA_TRATAMIENTOS(COD_TRATAMIENTO),
    CONSTRAINT FK_DESCRIPCION_DIAGNOSTICO_DIAGNOSTICO FOREIGN KEY (COD_DIAGNOSTICO) REFERENCES EIFA_DIAGNOSTICO(COD_DIAGNOSTICO)
);

CREATE TABLE EIFA_DIAGNOSTICO (
    COD_DIAGNOSTICO NUMBER,
    RUT_PACIENTE NUMBER,
    COD_MEDICO NUMBER,
    COD_MEDICAMENTO NUMBER,
    FECHA DATE,
    CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (COD_DIAGNOSTICO),
    CONSTRAINT FK_DIAGNOSTICO_PACIENTE FOREIGN KEY (RUT_PACIENTE) REFERENCES MJVA_PACIENTES(RUT_PACIENTE),
    CONSTRAINT FK_DIAGNOSTICO_MEDICO FOREIGN KEY (COD_MEDICO) REFERENCES TFPC_MEDICO(COD_MEDICO),
    CONSTRAINT FK_DIAGNOSTICO_MEDICAMENTO FOREIGN KEY (COD_MEDICAMENTO) REFERENCES EIFA_MEDICAMENTOS(COD_MEDICAMENTO)
);

CREATE TABLE MJVA_HISTORIAL_MEDICO_PACIENTE(
    ID_HISTORIAL NUMBER,
    RUT_PACIENTE NUMBER,
    COD_DIAGNOSTICO NUMBER,
    COD_TRATAMIENTOS NUMBER,
    COD_ENFERMEDADES NUMBER,
    MEDICAMENTOS VARCHAR2(500),
    CONSTRAINT PK_ID_HISTORIAL PRIMARY KEY(ID_HISTORIAL),
    CONSTRAINT FK_RUT_PACIENTE FOREIGN KEY(RUT_PACIENTE) REFERENCES MJVA_PACIENTES(RUT_PACIENTE),
    CONSTRAINT FK_COD_DIAGNOSTICO FOREIGN KEY(COD_DIAGNOSTICO) REFERENCES EIFA_DIAGNOSTICO(COD_DIAGNOSTICO),
    CONSTRAINT FK_COD_TRATAMIENTOS FOREIGN KEY(COD_TRATAMIENTOS) REFERENCES MJVA_TRATAMIENTOS(COD_TRATAMIENTO),
    CONSTRAINT FK_COD_ENFERMEDADES FOREIGN KEY(COD_ENFERMEDADES) REFERENCES MJVA_ENFERMEDADES(COD_ENFERMEDADES)
);

CREATE TABLE MJVA_CITAS_MEDICAS(
    ID_CITA NUMBER,
    COD_MEDICO NUMBER,
    RUT_PACIENTE NUMBER,
    HORA TIMESTAMP,
    FECHA DATE,
    CONSTRAINT PK_ID_CITA_MEDICAS PRIMARY KEY(ID_CITA),
    CONSTRAINT FK_CITAS_MEDICO FOREIGN KEY(COD_MEDICO) REFERENCES TFPC_MEDICO(COD_MEDICO),
    CONSTRAINT FK_CITAS_PACIENTE FOREIGN KEY(RUT_PACIENTE) REFERENCES MJVA_PACIENTES(RUT_PACIENTE)
);

CREATE TABLE MJVA_PROCEDIMIENTO(
    COD_PROCEDIMIENTO NUMBER,
    COD_PERSONAL NUMBER,
    RUT_PACIENTE NUMBER,
    COD_EQUIPO_MEDICO NUMBER,
    COD_MEDICO NUMBER,
    COD_VALOR NUMBER,
    COD_TIPO_PROCEDIMIENTO NUMBER,
    CONSTRAINT PK_PROCEDIMIENTO_PROCEDIMIENTO PRIMARY KEY(COD_PROCEDIMIENTO),
    CONSTRAINT FK_PROCEDIMIENTO_PERSONAL FOREIGN KEY(COD_PERSONAL) REFERENCES TFPC_PERSONAL(COD_PERSONAL),
    CONSTRAINT FK_PROCEDIMIENTO_PACIENTE FOREIGN KEY(RUT_PACIENTE) REFERENCES MJVA_PACIENTES(RUT_PACIENTE),
    CONSTRAINT FK_PROCEDIMIENTO_EQUIPO_MEDICO FOREIGN KEY(COD_EQUIPO_MEDICO) REFERENCES MJVA_EQUIPO_MEDICO(COD_EQUIPO_MEDICO),
    CONSTRAINT FK_PROCEDIMIENTO_MEDICO FOREIGN KEY(COD_MEDICO) REFERENCES TFPC_MEDICO(COD_MEDICO),
    CONSTRAINT FK_PROCEDIMIENTO_VALOR FOREIGN KEY(COD_VALOR) REFERENCES MJVA_VALOR(COD_VALOR),
    CONSTRAINT FK_PROCETIMIENTO_TIPO_PROCEDIMIENTO FOREIGN KEY(COD_TIPO_PROCEDIMIENTO) REFERENCES MJVA_TIPO_PROCEDIMIENTO(COD_TIPO_PROCEDIMIENTO)
);

CREATE TABLE EIFA_CABECERA_BOLETA (
    COD_BOLETA NUMBER,
    COD_AUXILIAR NUMBER,
    COD_FORMA_PAGO NUMBER,
    TOTAL_A_PAGAR NUMBER,
    RUT_PACIENTE NUMBER,
    FECHA DATE,
    CONSTRAINT PK_CABECERA PRIMARY KEY (COD_BOLETA),
    CONSTRAINT FK_CABECERA_AUXILIAR FOREIGN KEY (COD_AUXILIAR) REFERENCES EIFA_AUXILIARES(COD_AUXILIAR),
    CONSTRAINT FK_CABECERA_MEDIOPAGO FOREIGN KEY (COD_FORMA_PAGO) REFERENCES EIFA_FORMA_DE_PAGO(COD_FORMA_PAGO),
    CONSTRAINT FK_CABECERA_PACIENTE FOREIGN KEY (RUT_PACIENTE) REFERENCES MVJA_PACIENTES(RUT_PACIENTE)
);

CREATE TABLE EIFA_CUERPO_BOLETA (
    COD_CUERPO NUMBER,
    COD_MEDICAMENTO NUMBER,
    COD_PROCEDIMIENTO NUMBER,
    COD_BOLETA NUMBER,
    CANTIDAD NUMBER,
    VALOR NUMBER,
    CONSTRAINT PK_CUERPO_BOLETA PRIMARY KEY (COD_CUERPO),
    CONSTRAINT FK_CUERPO_MEDICAMENTO FOREIGN KEY (COD_MEDICAMENTO) REFERENCES EIFA_MEDICAMENTOS(COD_MEDICAMENTO),
    CONSTRAINT FK_CUERPO_PROCEDIMIENTO FOREIGN KEY (COD_PROCEDIMIENTO) REFERENCES MVJA_PROCEDIMIENTO(COD_PROCEDIMIENTO),
    CONSTRAINT FK_CUERPO_BOLETA FOREIGN KEY (COD_BOLETA) REFERENCES EIFA_CABECERA_BOLETA(COD_BOLETA)
);